%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gcox0\Google Drive\Teaching\2021_F\MA310\MATLAB\TTT Battle App\TTT_Tourney_Results.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 09-Dec-2021 17:16:18

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 22);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "B3:W25";

% Specify column names and types
opts.VariableNames = ["VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "TicTacToeAITournament", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23"];
opts.VariableTypes = ["string", "double", "double", "string", "double", "double", "string", "double", "double", "string", "double", "double", "string", "double", "double", "string", "double", "double", "string", "double", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "VarName5", "VarName8", "VarName11", "VarName14", "VarName17", "VarName20", "VarName23"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName2", "VarName5", "VarName8", "VarName11", "VarName14", "VarName17", "VarName20", "VarName23"], "EmptyFieldRule", "auto");

% Import the data
TTTTourneyResults = readtable("C:\Users\gcox0\Google Drive\Teaching\2021_F\MA310\MATLAB\TTT Battle App\TTT_Tourney_Results.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts