function G = HW5P11_construct_graph(vertex_info, edge_info, graph_name)

    edges = [edge_info.src edge_info.dst];

    if ~isfield(vertex_info, 'label')
        vertex_info.label = string(num2str((1:max(max(edges)))'));
    end
    
    vertices = 1:length(vertex_info.label);
    
    if ~isfield(edge_info, 'label')
        edge_info.label = "e_" + string(num2str((1:height(edges))'));
    end

    % G = struct( ...
    %     'name', graph_name, ...
    %     'vertices', vertices', ...
    %     'v_labels', vertex_info.label, ...
    %     'v_data', vertex_info.data, ...
    %     'v_count', length(vertices), ...
    %     'edges', edges, ...
    %     'e_labels', edge_info.label, ...
    %     'e_wts', edge_info.wt, ...
    %     'e_count', height(edges) ...
    %     );

    G = struct( ...
        'vertices', vertices', ...
        'n', length(vertices), ...
        'edges', edges, ...
        'm', height(edges) ...
        );

    G.adj_mat   = HW5P1_adjacency_matrix(G);
    G.inc_mat   = HW5P2_incidence_matrix(G);
    G.degrees   = HW5P3_vertex_degrees(G);
    G.simple    = HW5P5_is_simple(G);
    G.has_cycle = HW5P6_has_cycle(G);
    G.connected = HW5P8_is_connected(G);
    G.eulerian  = HW5P4_is_eulerian(G);
    G.tree      = HW5P9_is_tree(G);
    G.bipartite = HW5P10_is_bipartite(G);
    
end