clear all; close all; clc;

if exist('line_db.mat','file')
    load('line_db.mat');
else
    line_db.line1 = struct( ...
        'eqn', '', ...
        'slope', 0, ...
        'y_intercept', 0, ...
        'x_intercept', 0 ...
        );
end

task_options = [ ...
    'Options:            '; ...
    '  A. Add a new line.'; ...
    '  B. View Lines.    '; ...
    '  C. Plot a line.   '; ...
    ];

disp(task_options)

while true

    task = input('What do you want to do?');

    if task == 'A'

        

end
%save('line_db.mat', 'line_db')
