function HW4P3_update_board(state)
        
    if state.player == 1
    
        text( ...
            state.x_click + 0.206, ...
            state.y_click + 0.525, ...
            'X', 'fontsize', 80, 'color', 'blue' ...
            )

    else

        text( ...
            state.x_click + 0.156, ...
            state.y_click + 0.525, ...
            'O', 'fontsize', 80, 'color', 'red' ...
            )
    end

end